### ISSUE TITLE
Allow developers to access the Order resource

### ISSUE THREAD

**Issue by gregkorte** [Hairtrigger-Bunnies/bangazon-api#5]
Verbs to be supported

1. GET
1. POST
1. PUT
1. DELETE

User should be able to GET a list, and GET a single item.

**Comment by AspenHumphrey** [comment]
Aspen and Jevon working on creating an order with a product that goes to the order product type

**Comment by AspenHumphrey** [comment]
associated branch: ahjt-orderProducts
